// GENERATED CODE - DO WHATEVER YOU WANT WITH IT
// **************************************************************************
// Total assets: 8
// Generated by flutter_assets_generator extension for VS Code
// @mrasityilmaz
// **************************************************************************


class Assets {

	static const String export_icon_svg = 'assets/icons/export-icon.svg';

	static const String home_icon_svg = 'assets/icons/home-icon.svg';

	static const String info_icon_svg = 'assets/icons/info-icon.svg';

	static const String os_icon_svg = 'assets/icons/os-icon.svg';

	static const String privacy_icon_svg = 'assets/icons/privacy-icon.svg';

	static const String settings_icon_svg = 'assets/icons/settings-icon.svg';

	static const String star_icon_svg = 'assets/icons/star-icon.svg';

	static const String terms_icon_svg = 'assets/icons/terms-icon.svg';

}
